#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Sep 10 13:28:22 CDT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Axi4LiteReg_tb_behav -key {Behavioral:sim_1:Functional:Axi4LiteReg_tb} -tclbatch Axi4LiteReg_tb.tcl -view /home/garry/School/year-25-26/digital-system-deisgn/Digtal-System-P1/Axi4LiteRegs/Axi4LiteReg_tb_behav.wcfg -log simulate.log"
xsim Axi4LiteReg_tb_behav -key {Behavioral:sim_1:Functional:Axi4LiteReg_tb} -tclbatch Axi4LiteReg_tb.tcl -view /home/garry/School/year-25-26/digital-system-deisgn/Digtal-System-P1/Axi4LiteRegs/Axi4LiteReg_tb_behav.wcfg -log simulate.log

